-- Migration: create fiches_suivi table
CREATE TABLE IF NOT EXISTS fiches_suivi (
  id TEXT PRIMARY KEY,
  client_id TEXT REFERENCES clients(id) ON DELETE SET NULL,
  date_creation DATE,
  motif TEXT,
  sexe VARCHAR(1),
  age INTEGER,
  temperature DECIMAL(5,2),
  tension VARCHAR(20),
  poids DECIMAL(5,2),
  douleur TEXT,
  type_douleur TEXT,
  siege_douleur TEXT,
  diagnostic TEXT,
  examen_physique TEXT,
  bilan_vasculaire TEXT,
  bilan_neurologique TEXT,
  bilan_articulaire TEXT,
  bilan_musculaire TEXT,
  evaluation_fonctionnelle TEXT,
  facteurs_psychologiques TEXT,
  objectifs TEXT,
  plan_soins TEXT,
  note_complementaire TEXT,
  created_by TEXT,
  updated_by TEXT,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
